version: '3.8'

services:
  nprobe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nprobe-probe
    
    # Required for packet capture and PF_RING
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - IPC_LOCK
    
    # Mount necessary directories and files
    volumes:
      # Configuration
      - ./config:/opt/nprobe/config:rw
      - ./logs:/opt/nprobe/logs:rw
      
      # License files
      - ./licenses:/opt/nprobe/licenses:ro
      
      # Kernel modules and headers
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      
      # PF_RING specific
      - /dev:/dev:rw
      - /proc:/proc:ro
      - /sys:/sys:ro
      
    # Environment configuration
    environment:
      - NPROBE_CONFIG_FILE=/opt/nprobe/config/nprobe-config.json
      - NPROBE_USE_PFRING=true
      - NPROBE_DRIVER=i40e  # Adjust based on your NIC
      - NPROBE_INSTANCES=1  # Number of nprobe instances
      - NPROBE_RSS_QUEUES=4 # Number of RSS queues
      
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4.0'
        reservations:
          memory: 1G
          cpus: '2.0'
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "nprobe"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

    # Ensure proper shutdown
    stop_grace_period: 30s
