version: '3.8'

services:
  nprobe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nprobe-probe
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - IPC_LOCK
    volumes:
      - ./config:/opt/nprobe/config:rw
      - ./logs:/opt/nprobe/logs:rw
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      - /dev:/dev:rw
    environment:
      - NPROBE_USE_PFRING=true
      # Define other environment variables like NPROBE_INTERFACES here if needed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    stop_grace_period: 30s
