version: '3.8'

services:
  nprobe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nprobe-flow-exporter
    # Required for packet capture and kernel module loading
    privileged: true
    # Network mode host for direct access to network interfaces
    network_mode: host
    # Mount configuration and persistent data
    volumes:
      - ./config:/opt/nprobe/config:ro
      - ./logs:/opt/nprobe/logs:rw
      - ./licenses:/opt/nprobe/licenses:ro
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
    # Environment variables
    environment:
      - NPROBE_CONFIG_FILE=/opt/nprobe/config/nprobe-config.json
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'
    # Restart policy
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-f", "nprobe"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
